CREATE TABLE [BHIP].[Panel_PBI] (
    [MVIPersonSID]            INT            NULL,
    [PatientICN]              VARCHAR (50)   NULL,
    [PatientName]             VARCHAR (200)  NULL,
    [LastFour]                CHAR (4)       NULL,
    [DateOfBirth]             DATE           NULL,
    [Team]                    VARCHAR (50)   NULL,
    [MHTC_Provider]           VARCHAR (100)  NULL,
    [RelationshipStartDate]   DATE           NULL,
    [ChecklistID]             NVARCHAR (30)  NULL,
    [OverdueforFill]          INT            NULL,
    [NoMHAppointment6mo]      INT            NULL,
    [TotalMissedAppointments] INT            NULL,
    [OverdueForLab]           INT            NULL,
    [AcuteEventScore]         INT            NULL,
    [ChronicCareScore]        INT            NULL,
    [ActiveEpisode]           TINYINT        NULL,
    [LastEvent]               DATE           NULL,
    [Overdue_Any]             INT            NULL,
    [LastBHIPContact]         DATE           NULL,
    [ReportMode]              VARCHAR (10)   NULL,
    [CurrentlyAdmitted]       VARCHAR (3)    NULL,
    [FLOWEligible]            VARCHAR (3)    NOT NULL,
    [Facility]                NVARCHAR (255) NULL,
    [Code]                    NVARCHAR (255) NULL,
    [VisitNUmber]             BIGINT         NULL,
    [AppointmentDateTime]     DATETIME2 (0)  NULL,
    [AppointmentLocationName] VARCHAR (50)   NULL,
    [RedactedName]            VARCHAR (200)  NULL,
    [RedactedDate]            DATE           NULL,
    [AppointmentDayFormatted] VARCHAR (50)   NULL,
    [AppointmentDate_Slicer]  DATE           NULL,
    [Homeless]                VARCHAR (25)   NULL
);

