CREATE TABLE [Present].[Medications] (
    [PatientPersonSID]                INT           NULL,
    [MVIPersonSID]                    INT           NULL,
    [RxOutpatSID]                     BIGINT        NULL,
    [DerivedPersonOrderSID]           BIGINT        NULL,
    [MedMgrPersonOrderSID]            BIGINT        NULL,
    [Sta6a]                           VARCHAR (8)   NULL,
    [ChecklistID]                     VARCHAR (5)   NULL,
    [IssueDate]                       DATE          NULL,
    [LastReleaseDateTime]             DATETIME2 (0) NULL,
    [PrescriberSID]                   INT           NULL,
    [PrescriberName]                  VARCHAR (100) NULL,
    [RxStatus]                        VARCHAR (50)  NULL,
    [DrugStatus]                      VARCHAR (50)  NULL,
    [DrugSource]                      VARCHAR (5)   NULL,
    [NationalDrugSID]                 BIGINT        NULL,
    [VUID]                            VARCHAR (50)  NULL,
    [Sta3n]                           SMALLINT      NOT NULL,
    [DrugNameWithDose]                VARCHAR (100) NULL,
    [DrugNameWithoutDose]             VARCHAR (100) NULL,
    [DrugNameWithoutDoseSID]          BIGINT        NULL,
    [CSFederalSchedule]               VARCHAR (50)  NULL,
    [PrimaryDrugClassCode]            VARCHAR (100) NULL,
    [StrengthNumeric]                 DECIMAL (18)  NULL,
    [DosageForm]                      VARCHAR (100) NULL,
    [AchAntiHist_Rx]                  BIT           NULL,
    [AChAD_Rx]                        BIT           NULL,
    [AChALL_Rx]                       BIT           NULL,
    [AlcoholPharmacotherapy_Rx]       BIT           NULL,
    [AlcoholPharmacotherapy_notop_Rx] BIT           NULL,
    [Alprazolam_Rx]                   BIT           NULL,
    [Antidepressant_Rx]               BIT           NULL,
    [SSRI_SNRI_Rx]                    BIT           NULL,
    [Antipsychotic_Geri_Rx]           BIT           NULL,
    [Antipsychotic_Rx]                BIT           NULL,
    [AntipsychoticSecondGen_Rx]       BIT           NULL,
    [Anxiolytics_Rx]                  BIT           NULL,
    [Benzodiazepine_Rx]               BIT           NULL,
    [Bowel_Rx]                        BIT           NULL,
    [Clonazepam_Rx]                   BIT           NULL,
    [Lorazepam_Rx]                    BIT           NULL,
    [Mirtazapine_Rx]                  BIT           NULL,
    [MPRCalculated_Rx]                BIT           NULL,
    [MoodStabilizer_Rx]               BIT           NULL,
    [MoodStabilizer_GE3_Rx]           BIT           NULL,
    [NaltrexoneINJ_Rx]                BIT           NULL,
    [Olanzapine_Rx]                   BIT           NULL,
    [Opioid_Rx]                       BIT           NULL,
    [OpioidAgonist_Rx]                BIT           NULL,
    [PainAdjAnticonvulsant_Rx]        BIT           NULL,
    [PainAdjTCA_Rx]                   BIT           NULL,
    [PainAdjSNRI_Rx]                  BIT           NULL,
    [PDSIRelevant_Rx]                 BIT           NULL,
    [Prazosin_Rx]                     BIT           NULL,
    [Prochlorperazine_Rx]             BIT           NULL,
    [Promethazine_Rx]                 BIT           NULL,
    [Psychotropic_Rx]                 BIT           NULL,
    [Reach_AntiDepressant_Rx]         BIT           NULL,
    [Reach_AntiPsychotic_Rx]          BIT           NULL,
    [Reach_opioid_Rx]                 BIT           NULL,
    [Reach_statin_Rx]                 BIT           NULL,
    [Reach_SedativeAnxiolytic_Rx]     BIT           NULL,
    [SedatingPainORM_Rx]              BIT           NULL,
    [SedativeOpioid_Rx]               BIT           NULL,
    [Sedative_zdrug_Rx]               BIT           NULL,
    [Stimulant_Rx]                    BIT           NULL,
    [StimulantADHD_Rx]                BIT           NULL,
    [TobaccoPharmacotherapy_Rx]       BIT           NULL,
    [Tramadol_Rx]                     BIT           NULL,
    [Zolpidem_Rx]                     BIT           NULL,
    [Methadone_Rx]                    BIT           NULL,
    [OpioidForPain_Rx]                BIT           NULL,
    [NaloxoneKit_Rx]                  BIT           NULL,
    [SSRI_Rx]                         BIT           NULL,
    [ControlledSubstance]             BIT           NULL,
    [CNS_Depress_Rx]                  BIT           NULL,
    [CNS_ActiveMed_Rx]                BIT           NULL,
    [CHOICE]                          BIT           NULL
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCIX_Medications]
    ON [Present].[Medications];

