SELECT [Label]
      , [SnippetID]
      , [Term]
      , [PatientSID]
      , [Sta3n]
      , [ReferenceDateTime]
      , [TIUdocumentSID]
      , [NoteAndSnipOffset]
      , [TargetClass]
      , [TIUstandardTitle]
      , [Snippet]
      , [VisitSID]
      , [TargetSubClass]
      , [TermID]
      , [OpCode]
      , [FileDate]
FROM [OMHSP_PERC_PDW].[App].[HDAP_NLP_OMHSP] with (nolock)