CREATE TABLE [PRF_HRS].[PatientReport_v02] (
    [MVIPersonSID]             INT            NOT NULL,
    [ActiveFlag]               CHAR (1)       NULL,
    [InitialActivation]        DATETIME2 (7)  NULL,
    [LastActionDateTime]       DATETIME2 (0)  NULL,
    [MostRecentActivation]     DATETIME2 (0)  NULL,
    [OwnerChecklistID]         VARCHAR (5)    NOT NULL,
    [CernerVistADiff]          VARCHAR (125)  NULL,
    [CernerOwnerChecklistID]   VARCHAR (5)    NULL,
    [LastActionType]           TINYINT        NULL,
    [LastActionDescription]    VARCHAR (32)   NULL,
    [IP_Current]               INT            NULL,
    [IP_DateTime]              DATETIME2 (0)  NULL,
    [IP_BedSection]            VARCHAR (MAX)  NULL,
    [IP_Location]              NVARCHAR (510) NULL,
    [LastSafetyPlanDateTime]   DATETIME2 (0)  NULL,
    [LastFlagReviewDateTime]   DATETIME2 (0)  NULL,
    [SuicideBehaviorReport]    DATETIME2 (0)  NULL,
    [SuicideEventCount]        TINYINT        NULL,
    [CSRE]                     DATETIME2 (0)  NULL,
    [VisitsM1]                 INT            NULL,
    [VisitsM2]                 INT            NULL,
    [VisitsM3]                 INT            NULL,
    [SP_DateTime]              DATETIME2 (0)  NULL,
    [SP_Met]                   INT            NULL,
    [SP_DayCountAbs]           INT            NULL,
    [NextReviewDate]           DATETIME2 (0)  NULL,
    [MinReviewDate]            DATE           NULL,
    [MaxReviewDate]            DATE           NULL,
    [AssignedSPC]              VARCHAR (MAX)  NULL,
    [LastVisitDateTime]        DATETIME2 (0)  NULL,
    [LastVisitDetail]          VARCHAR (MAX)  NULL,
    [NextApptDateTime]         DATETIME2 (0)  NULL,
    [LastNoShowDateTime]       DATETIME2 (0)  NULL,
    [CountNS30Days]            INT            NULL,
    [FutureCancelDateTime]     DATETIME2 (0)  NULL,
    [FutureCancelApptDateTime] DATETIME2 (0)  NULL,
    [UnsuccessDate]            DATE           NULL,
    [UnsuccessCount]           INT            NULL,
    [SuccessDate]              DATE           NULL,
    [SuccessCount]             INT            NULL,
    [CaringLetters]            TINYINT        NULL,
    [SP2EligibleDate]          DATE           NULL,
    [SP2ConsultRequestDate]    DATE           NULL,
    [SP2ConsultActionable]     TINYINT        NULL,
    [StaffName_PCP]            VARCHAR (100)  NOT NULL,
    [CountPCP]                 INT            NOT NULL,
    [Sta6a_PCP]                VARCHAR (6)    NULL,
    [StaffName_MHTC]           VARCHAR (100)  NOT NULL,
    [CountMHTC]                INT            NOT NULL,
    [Sta6a_MHTC]               VARCHAR (6)    NULL,
    [Team_MHTC]                VARCHAR (50)   NULL,
    [SourceEHR]                VARCHAR (2)    NULL,
    [DateOfDeath]              DATE           NULL,
    [UpdateDate]               DATETIME       NOT NULL
);


GO
CREATE CLUSTERED INDEX [PRF_HRS_Report]
    ON [PRF_HRS].[PatientReport_v02]([MVIPersonSID] ASC) WITH (FILLFACTOR = 100);

