CREATE TABLE [ORM].[DoDOUDPatientReport] (
    [MVIPersonSID]                INT              NULL,
    [PatientICN]                  VARCHAR (50)     NULL,
    [EDIPI]                       VARCHAR (50)     NULL,
    [LastName]                    VARCHAR (50)     NULL,
    [FirstName]                   VARCHAR (50)     NULL,
    [MiddleName]                  VARCHAR (50)     NULL,
    [NameSuffix]                  VARCHAR (50)     NULL,
    [PatientName]                 VARCHAR (153)    NULL,
    [PatientSSN]                  VARCHAR (50)     NULL,
    [DateofBirth]                 DATE             NULL,
    [age]                         INT              NULL,
    [Gender]                      VARCHAR (50)     NULL,
    [StreetAddress1]              VARCHAR (100)    NULL,
    [StreetAddress2]              VARCHAR (100)    NULL,
    [City]                        VARCHAR (100)    NULL,
    [State]                       VARCHAR (22)     NULL,
    [Zip]                         VARCHAR (5)      NULL,
    [FYQ]                         VARCHAR (17)     NOT NULL,
    [CareType]                    VARCHAR (50)     NULL,
    [LastDoDDiagnosisDate]        DATE             NULL,
    [LastVADiagnosisDate]         DATE             NULL,
    [VisitDateTime]               DATE             NULL,
    [MaxDoDEncounter]             DATE             NULL,
    [Sta3n]                       INT              NULL,
    [ChecklistID]                 VARCHAR (5)      NULL,
    [VISN]                        INT              NULL,
    [Facility]                    NVARCHAR (100)   NULL,
    [OpioidForPain_Rx]            BIT              NULL,
    [OUD]                         INT              NULL,
    [OUD_DoD]                     INT              NOT NULL,
    [SUDdx_poss]                  BIT              NULL,
    [Hospice]                     BIT              NULL,
    [Anxiolytics_Rx]              BIT              NULL,
    [RiskScore]                   DECIMAL (38, 15) NULL,
    [RiskScoreAny]                DECIMAL (38, 15) NULL,
    [RiskScoreOpioidSedImpact]    DECIMAL (38, 6)  NULL,
    [RiskScoreAnyOpioidSedImpact] DECIMAL (38, 6)  NULL,
    [RiskCategory]                INT              NULL,
    [RiskAnyCategory]             INT              NULL,
    [RM_ActiveTherapies_Key]      INT              NULL,
    [RM_ActiveTherapies_Date]     DATETIME2 (0)    NULL,
    [RM_ChiropracticCare_Key]     INT              NULL,
    [RM_ChiropracticCare_Date]    DATETIME2 (0)    NULL,
    [RM_OccupationalTherapy_Key]  INT              NULL,
    [RM_OccupationalTherapy_Date] DATETIME2 (0)    NULL,
    [RM_OtherTherapy_Key]         INT              NULL,
    [RM_OtherTherapy_Date]        DATETIME2 (0)    NULL,
    [RM_PhysicalTherapy_Key]      INT              NULL,
    [RM_PhysicalTherapy_Date]     DATETIME2 (0)    NULL,
    [RM_SpecialtyTherapy_Key]     INT              NULL,
    [RM_SpecialtyTherapy_Date]    DATETIME2 (0)    NULL,
    [RM_PainClinic_Key]           INT              NULL,
    [RM_PainClinic_Date]          DATETIME2 (0)    NULL,
    [CAM_Key]                     INT              NULL,
    [CAM_Date]                    DATETIME2 (0)    NULL,
    [riosordscore]                INT              NULL,
    [riosordriskclass]            INT              NULL,
    [PatientRecordFlag_Suicide]   INT              NOT NULL,
    [REACH_01]                    INT              NOT NULL,
    [REACH_Past]                  INT              NOT NULL,
    [RiskCategoryLabel]           VARCHAR (50)     NULL,
    [RiskAnyCategoryLabel]        VARCHAR (50)     NULL,
    [ODPastYear]                  INT              NOT NULL,
    [ODdate]                      INT              NULL,
    [STORM]                       INT              NULL,
    [Census]                      INT              NOT NULL,
    [InpatientFacility]           NVARCHAR (100)   NULL,
    [MedLocation]                 NVARCHAR (10)    NULL,
    [MedLocationName]             NVARCHAR (255)   NULL,
    [MedLocationColor]            NVARCHAR (255)   NULL,
    [ProviderLocation]            NVARCHAR (30)    NULL,
    [ProviderLocationName]        NVARCHAR (255)   NULL,
    [ProviderLocationColor]       NVARCHAR (255)   NULL,
    [AppointmentLocation]         VARCHAR (5)      NULL,
    [AppointmentLocationName]     NVARCHAR (255)   NULL,
    [AppointmentLocationColor]    NVARCHAR (255)   NULL,
    [VisitLocation]               VARCHAR (5)      NULL,
    [VisitLocationName]           NVARCHAR (255)   NULL,
    [VisitLocationColor]          NVARCHAR (255)   NULL,
    [Locations]                   NVARCHAR (30)    NULL,
    [LocationName]                NVARCHAR (255)   NULL,
    [LocationsColor]              NVARCHAR (255)   NULL,
    [ActiveMOUD_Patient]          INT              NULL,
    [NonVA_Meds]                  INT              NULL,
    [DxId]                        BIGINT           NULL,
    [Diagnosis]                   VARCHAR (1000)   NULL,
    [ColumnName]                  NVARCHAR (128)   NULL,
    [Category]                    VARCHAR (100)    NULL,
    [MedType]                     VARCHAR (34)     NULL,
    [MedID]                       BIGINT           NULL,
    [DrugNameWithoutDose]         VARCHAR (150)    NULL,
    [PrescriberName]              VARCHAR (150)    NULL,
    [CHOICE]                      INT              NULL,
    [MitigationID]                SMALLINT         NULL,
    [MitigationIDRx]              FLOAT (53)       NULL,
    [PrintNameRx]                 VARCHAR (100)    NULL,
    [CheckedRx]                   INT              NULL,
    [RedRx]                       INT              NULL,
    [MetricInclusion]             BIT              NULL,
    [RiskMitigation]              VARCHAR (113)    NULL,
    [DetailsText]                 VARCHAR (60)     NULL,
    [DetailsDate]                 DATETIME2 (7)    NULL,
    [Checked]                     SMALLINT         NOT NULL,
    [Red]                         BIT              NOT NULL,
    [GroupID]                     INT              NULL,
    [GroupType]                   VARCHAR (25)     NULL,
    [ProviderName]                VARCHAR (100)    NULL,
    [ProviderSID]                 INT              NULL,
    [AppointmentID]               BIGINT           NULL,
    [AppointmentType]             VARCHAR (24)     NULL,
    [AppointmentStop]             VARCHAR (100)    NULL,
    [AppointmentDatetime]         DATETIME2 (0)    NULL,
    [VisitStop]                   VARCHAR (100)    NULL,
    [MonthsinTreatment]           VARCHAR (30)     NULL,
    [SourceEHR]                   VARCHAR (2)      NULL,
    [Z79891]                      INT              NOT NULL
);








GO
