CREATE TABLE [ORM].[ORM_DoDOUDZ79891] (
    [MVIPersonSID] INT NULL,
    [Z79891]       INT NOT NULL
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCIX_ORM_DoDOUDZ79891]
    ON [ORM].[ORM_DoDOUDZ79891];

