CREATE TABLE [SPPRITE].[PatientDetail] (
    [MVIPersonSID]                       INT             NULL,
    [PatientICN]                         VARCHAR (50)    NULL,
    [PatientName]                        VARCHAR (123)   NULL,
    [Last4]                              VARCHAR (4)     NULL,
    [Age]                                NUMERIC (18)    NULL,
    [Gender]                             VARCHAR (50)    NULL,
    [PercentServiceConnect]              VARCHAR (10)    NULL,
    [ServiceSeparationDate]              DATE            NULL,
    [CommunityStatusDateTime]            DATE            NULL,
    [SensitiveFlag]                      BIT             NULL,
    [RiskFactors]                        VARCHAR (100)   NULL,
    [Homeless]                           BIT             NULL,
    [DateofDeath]                        DATETIME2 (0)   NULL,
    [CSSRS_ID_Date]                      DATETIME2 (0)   NULL,
    [CSSRS_ID_ChecklistID]               VARCHAR (5)     NULL,
    [CSSRS_ID_Facility]                  VARCHAR (510)   NULL,
    [CSRE_ID_DateTime]                   DATETIME2 (0)   NULL,
    [CSRE_ID_Acute]                      VARCHAR (50)    NULL,
    [CSRE_ID_Chronic]                    VARCHAR (50)    NULL,
    [CSRE_ID_ChecklistID]                VARCHAR (5)     NULL,
    [CSRE_ID_Facility]                   VARCHAR (510)   NULL,
    [CSRE_DateTime]                      DATETIME2 (0)   NULL,
    [CSRE_ClinImpressAcute]              VARCHAR (50)    NULL,
    [CSRE_ClinImpressChronic]            VARCHAR (50)    NULL,
    [CSRE_ChecklistID]                   VARCHAR (5)     NULL,
    [CSRE_Facility]                      VARCHAR (510)   NULL,
    [CSSRS_Date]                         DATETIME2 (0)   NULL,
    [display_CSSRS]                      BIT             NULL,
    [CSSRS_ChecklistID]                  VARCHAR (5)     NULL,
    [CSSRS_Facility]                     NVARCHAR (510)  NULL,
    [CSSRS_CSREDateTime]                 DATETIME2 (0)   NULL,
    [AUDITC_ChecklistID]                 VARCHAR (5)     NULL,
    [AUDITC_Facility]                    NVARCHAR (510)  NULL,
    [AUDITC_SurveyDate]                  DATE            NULL,
    [AUDITC_SurveyResult]                VARCHAR (30)    NULL,
    [CAN_HospRiskDate]                   DATE            NULL,
    [CAN_cHosp_90d]                      INT             NULL,
    [CAN_MortRiskDate]                   DATE            NULL,
    [CAN_cMort_90d]                      INT             NULL,
    [SafetyPlanDateTime]                 DATETIME2 (0)   NULL,
    [SafetyPlan_Decline]                 BIT             NULL,
    [SafetyPlan_Review]                  BIT             NULL,
    [SafetyPlan_ChecklistID]             VARCHAR (5)     NULL,
    [SafetyPlan_Facility]                NVARCHAR (510)  NULL,
    [RxTransitions_Antipsychotic]        INT             NULL,
    [RxTransitions_Antidepressant]       INT             NULL,
    [RxTransitions_Benzodiazepine]       INT             NULL,
    [RxTransitions_Sedative_zdrug]       INT             NULL,
    [RxTransitions_MoodStabilizer]       INT             NULL,
    [RxTransitions_Stimulant]            INT             NULL,
    [RxTransitions_OpioidForPain]        INT             NULL,
    [RxTransitions_OpioidAgonist]        INT             NULL,
    [RxTransitions_OtherControlledSub]   INT             NULL,
    [RxTransitions_MinDaysForSorting]    INT             NULL,
    [PatRecFlag_Status]                  VARCHAR (25)    NULL,
    [PatRecFlag_Date]                    DATETIME2 (0)   NULL,
    [PatRecFlag_ChecklistID]             VARCHAR (5)     NULL,
    [PatRecFlag_Facility]                VARCHAR (50)    NULL,
    [HRFLetters_EligDate]                DATE            NULL,
    [HRFLetters_Status]                  VARCHAR (50)    NULL,
    [Behavioral_ActiveFlag]              VARCHAR (15)    NULL,
    [Behavioral_ActionDateTime]          DATE            NULL,
    [Behavioral_ChecklistID]             VARCHAR (5)     NULL,
    [Behavioral_Facility]                NVARCHAR (510)  NULL,
    [RV_ChecklistID]                     VARCHAR (5)     NULL,
    [RV_Facility]                        NVARCHAR (510)  NULL,
    [SBOR_Date_Prep]                     VARCHAR (255)   NULL,
    [SBOR_DateFormattedNULL_Prep]        INT             NULL,
    [SBOR_ChecklistID_Prep]              VARCHAR (5)     NULL,
    [SBOR_Facility_Prep]                 VARCHAR (150)   NULL,
    [SBOR_Date_Att]                      VARCHAR (355)   NULL,
    [SBOR_DateFormattedNULL_Att]         INT             NULL,
    [SBOR_ChecklistID_Att]               VARCHAR (5)     NULL,
    [SBOR_Facility_Att]                  VARCHAR (150)   NULL,
    [SomaticTx_ChecklistID]              VARCHAR (5)     NULL,
    [SomaticTx_FacilityName]             VARCHAR (150)   NULL,
    [SomaticTx_Date]                     DATETIME2 (0)   NULL,
    [SomaticTx_Type]                     VARCHAR (50)    NULL,
    [PDE_InpatDate]                      DATETIME2 (0)   NULL,
    [PDE_ChecklistIDs]                   VARCHAR (25)    NULL,
    [PDE_Disch_BedSecName]               VARCHAR (50)    NULL,
    [PDE_InpatChecklistID]               VARCHAR (5)     NULL,
    [PDE_InpatFacility]                  VARCHAR (50)    NULL,
    [Census]                             BIT             NULL,
    [InpatDate]                          DATETIME2 (0)   NULL,
    [InpatChecklistID]                   VARCHAR (5)     NULL,
    [InpatFacility]                      VARCHAR (50)    NULL,
    [Disch_BedSecName]                   VARCHAR (50)    NULL,
    [STORM]                              BIT             NULL,
    [STORM_RiskCategory]                 TINYINT         NULL,
    [STORM_RiskCategoryLabel]            VARCHAR (100)   NULL,
    [STORM_RMS_TimelyPerformed]          INT             NULL,
    [STORM_RMS_Denominator]              INT             NULL,
    [STORM_ChecklistIDs]                 VARCHAR (100)   NULL,
    [STORM_Facilities]                   VARCHAR (1000)  NULL,
    [SPED_DateTime]                      DATETIME2 (0)   NULL,
    [SPED_ChecklistiD]                   VARCHAR (5)     NULL,
    [SPED_Facility]                      VARCHAR (510)   NULL,
    [SRM_DateTime_success]               DATETIME2 (0)   NULL,
    [SRM_VeteranReached_recent]          TINYINT         NULL,
    [SRM_DateTime_recent]                DATETIME2 (0)   NULL,
    [LastEDVisit]                        DATETIME2 (0)   NULL,
    [PCPCount]                           TINYINT         NULL,
    [MHTCCount]                          TINYINT         NULL,
    [VCL_Call_Date]                      DATE            NULL,
    [VCL_ChecklistID]                    VARCHAR (5)     NULL,
    [VCL_Status]                         VARCHAR (50)    NULL,
    [HNHR]                               BIT             NULL,
    [HNHR_Facility]                      VARCHAR (510)   NULL,
    [OFR_LastVisitDate]                  DATE            NULL,
    [OFR_ChecklistID]                    VARCHAR (5)     NULL,
    [OFR_Facility]                       VARCHAR (510)   NULL,
    [OFR_FirstSPPRITEDate]               DATE            NULL,
    [OFR_NewPrior3Months]                BIT             NULL,
    [OFR_EligibilityFlag]                BIT             NULL,
    [OFR_OutreachDate_Recent]            DATE            NULL,
    [OFR_OutreachStatus_Recent]          VARCHAR (50)    NULL,
    [OFR_OutreachDate_Success]           DATE            NULL,
    [OFR_nursinghome]                    BIT             NULL,
    [MHengage]                           INT             NULL,
    [SMI_ReEngage_ChecklistID]           VARCHAR (5)     NULL,
    [SMI_ReEngage_Facility]              VARCHAR (510)   NULL,
    [SMI_ReEngage_Wave]                  INT             NULL,
    [DMC_count]                          INT             NULL,
    [DMC_TotalDebt]                      DECIMAL (15, 2) NULL,
    [DMC_MostRecentDate]                 DATE            NULL,
    [DMC_MostRecentLetter]               VARCHAR (510)   NULL,
    [DMC_DisplayMessage]                 INT             NULL,
    [MST_ChecklistID]                    VARCHAR (5)     NULL,
    [MST_ScreenDateTime]                 DATETIME2 (0)   NULL,
    [COMPACT_EpisodeBeginDate]           DATE            NULL,
    [COMPACT_EpisodeEndDate]             DATE            NULL,
    [COMPACT_EpisodeBeginSetting]        VARCHAR (50)    NULL,
    [COMPACT_InpatientEpisodeEndDate]    DATE            NULL,
    [COMPACT_OutpatientEpisodeBeginDate] DATE            NULL,
    [COMPACT_ActiveEpisode]              VARCHAR (10)    NULL,
    [COMPACT_ActiveEpisodeSetting]       VARCHAR (50)    NULL,
    [COMPACT_ChecklistID]                VARCHAR (5)     NULL,
    [COMPACT_Facility]                   VARCHAR (510)   NULL,
    [COMPACT_Eligible]                   VARCHAR (510)   NULL,
    [COMPACT_ConfirmedStart]             BIT             NULL,
    [COMPACT_EncounterCodes]             VARCHAR (510)   NULL,
    [NextPCApptICN]                      DATETIME2 (0)   NULL,
    [NextPCApptChecklistID_ICN]          VARCHAR (5)     NULL,
    [NextPCApptFacilityICN]              VARCHAR (510)   NULL,
    [NextMHApptICN]                      DATETIME2 (0)   NULL,
    [NextMHApptChecklistID_ICN]          VARCHAR (5)     NULL,
    [NextMHApptFacilityICN]              VARCHAR (510)   NULL,
    [LastPCVisitICN]                     DATETIME2 (0)   NULL,
    [LastPCVisitICN_Sta3n]               INT             NULL,
    [LastPCVisitICN_Facility]            VARCHAR (510)   NULL,
    [LastMHVisitICN]                     DATETIME2 (0)   NULL,
    [LastMHVisitICN_Sta3n]               INT             NULL,
    [LastMHVisitICN_Facility]            VARCHAR (510)   NULL,
    [LastMHVisitICN_StopCodeName]        VARCHAR (510)   NULL,
    [StreetAddress1]                     VARCHAR (100)   NULL,
    [StreetAddress2]                     VARCHAR (100)   NULL,
    [StreetAddress3]                     VARCHAR (50)    NULL,
    [City]                               VARCHAR (50)    NULL,
    [StateAbbrev]                        VARCHAR (50)    NULL,
    [Zip]                                VARCHAR (50)    NULL,
    [PatientResidence]                   VARCHAR (50)    NULL,
    [PatientCell]                        VARCHAR (50)    NULL,
    [SourceEHR]                          VARCHAR (2)     NULL,
    [RunDate]                            DATE            NULL
);








GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCIX_PatientDetail]
    ON [SPPRITE].[PatientDetail];

