CREATE TABLE [PDSI].[PatientQuickView] (
    [MVIPersonSID]     INT            NULL,
    [ChecklistID]      VARCHAR (5)    NULL,
    [Facility]         NVARCHAR (100) NULL,
    [SUD16]            INT            NULL,
    [ALC_top1]         INT            NULL,
    [GBENZO1]          INT            NULL,
    [BENZO_Opioid_OP]  INT            NULL,
    [BENZO_PTSD_OP]    INT            NULL,
    [BENZO_SUD_OP]     INT            NULL,
    [PDMP_Benzo]       INT            NULL,
    [Naloxone_StimUD]  INT            NULL,
    [STIMRX1]          INT            NULL,
    [CoRx_RxStim]      INT            NULL,
    [EBP_StimUD]       INT            NULL,
    [Off_Label_RxStim] INT            NULL,
    [ApptDateTime_PC]  DATETIME2 (0)  NULL,
    [ApptLocation_PC]  NVARCHAR (255) NULL,
    [ApptStop_PC]      VARCHAR (50)   NULL,
    [ApptDateTime_MH]  DATETIME2 (0)  NULL,
    [ApptLocation_MH]  NVARCHAR (255) NULL,
    [ApptStop_MH]      VARCHAR (50)   NULL,
    [PCP]              VARCHAR (202)  NULL,
    [PCPsid]           INT            NULL,
    [MHTC]             VARCHAR (202)  NULL,
    [MHTCsid]          INT            NULL,
    [BHIP]             VARCHAR (100)  NULL,
    [BHIPsid]          INT            NULL,
    [PACT]             VARCHAR (100)  NULL,
    [PACTsid]          INT            NULL,
    [PrescriberSID]    INT            NULL,
    [Prescriber]       VARCHAR (100)  NULL,
    [DrugName]         NVARCHAR (MAX) NULL,
    [PrescriberName]   NVARCHAR (MAX) NULL,
    [MedDrugStatus]    VARCHAR (50)   NULL,
    [MedRxStatus]      VARCHAR (50)   NULL,
    [MedIssueDate]     DATETIME2 (7)  NULL,
    [MedReleaseDate]   DATETIME2 (7)  NULL,
    [CLO1]             INT            NULL,
    [APDEM1]           INT            NULL,
    [APGLUC1]          INT            NULL,
    [Outpat]           VARCHAR (100)  NULL,
    [Outpatsid]        INT            NULL,
    [Inpat]            VARCHAR (100)  NULL,
    [Inpatsid]         INT            NULL,
    [VitalsDate]       DATETIME2 (0)  NULL,
    [UDSDate]          DATETIME2 (0)  NULL,
    [AUDCScore]        INT            NULL,
    [AUDCDate]         DATETIME2 (0)  NULL
);

