









CREATE VIEW [Common].[MasterPatient_VM]

AS
	SELECT a.[MVIPersonSID]
      ,a.[PatientICN]
      ,a.[PatientSSN]
      ,a.[EDIPI]
      ,a.[LastName]
      ,a.[FirstName]
      ,a.[MiddleName]
      ,a.[NameSuffix]
      ,a.[PreferredName]
      ,a.[PatientName]
      ,a.[LastFour]
      ,a.[NameFour]
      ,a.[PatientSSN_Hyphen]
      ,a.[DateOfBirth]
      ,a.[DateOfDeath]
      ,a.[DateOfDeath_SVeteran]
      ,a.[DateOfDeath_Combined]
      ,a.[Age]
      ,a.[Gender]
      ,a.[SelfIdentifiedGender]
      ,a.[DisplayGender]
      ,a.[SexualOrientation]
      ,a.[Pronouns]
      ,a.[MaritalStatus]
      ,a.[Veteran]
      ,a.[VHAEligibilityFlag]
      ,a.[SensitiveFlag]
      ,a.[PossibleTestPatient]
      ,a.[TestPatient]
      ,a.[Race]
      ,a.[PatientHeight]
      ,a.[HeightDate]
      ,a.[PatientWeight]
      ,a.[WeightDate]
      ,a.[PercentServiceConnect]
      ,a.[PeriodOfService]
      ,a.[BranchOfService]
      ,a.[OEFOIFStatus]
      ,a.[ServiceSeparationDate]
      ,a.[PriorityGroup]
      ,a.[PrioritySubGroup]
      ,a.[COMPACTEligible]
      ,a.[Homeless]
      ,a.[Hospice]
	  ,b.[PhoneNumber]
      ,b.[WorkPhoneNumber]
      ,b.[CellPhoneNumber]
      ,b.[TempPhoneNumber]
      ,b.[NextOfKinPhone]
      ,b.[NextOfKinPhone_Name]
      ,b.[EmergencyPhone]
      ,b.[EmergencyPhone_Name]
      ,b.[StreetAddress1]
      ,b.[StreetAddress2]
      ,b.[StreetAddress3]
      ,b.[City]
      ,b.[State]
      ,b.[Zip]
      ,b.[Country]
      ,b.[GISURH]
      ,b.[County]
      ,b.[CountyFIPS]
      ,b.[TempStreetAddress1]
      ,b.[TempStreetAddress2]
      ,b.[TempStreetAddress3]
      ,b.[TempCity]
      ,b.[TempStateAbbrev]
      ,b.[TempPostalCode]
	  ,b.[TempCountry]
	  ,b.[MailStreetAddress1]
      ,b.[MailStreetAddress2]
      ,b.[MailStreetAddress3]
      ,b.[MailCity]
      ,b.[MailState]
      ,b.[MailZip]
      ,a.[SourceEHR]
	FROM [Common].[MasterPatient_Patient] a WITH (NOLOCK)
	LEFT JOIN [Common].[MasterPatient_Contact] b WITH (NOLOCK)
		ON a.MVIPersonSID=b.MVIPersonSID
	WHERE a.MVIPersonSID > 0