CREATE TABLE [SMI].[PatientReport] (
    [MVIPersonSID]                        INT            NOT NULL,
    [PatientICN]                          VARCHAR (50)   NULL,
    [LastName]                            VARCHAR (50)   NULL,
    [FirstName]                           VARCHAR (50)   NULL,
    [PatientName]                         VARCHAR (200)  NULL,
    [LastFour]                            CHAR (4)       NULL,
    [Age]                                 INT            NULL,
    [Gender]                              VARCHAR (50)   NULL,
    [Veteran]                             BIT            NULL,
    [PossibleTestPatient]                 BIT            NULL,
    [TestPatient]                         BIT            NULL,
    [PhoneNumber]                         VARCHAR (50)   NULL,
    [StreetAddress1]                      VARCHAR (100)  NULL,
    [StreetAddress2]                      VARCHAR (100)  NULL,
    [City]                                VARCHAR (50)   NULL,
    [State]                               VARCHAR (22)   NULL,
    [Zip]                                 VARCHAR (5)    NULL,
    [PercentServiceConnect]               VARCHAR (10)   NULL,
    [Homeless]                            BIT            NULL,
    [Homestation_ChecklistID]             VARCHAR (5)    NULL,
    [Sta3n]                               SMALLINT       NULL,
    [Schiz_dx]                            INT            NULL,
    [Schiz_dx_date]                       DATE           NULL,
    [Bipolar_dx]                          INT            NULL,
    [Bipolar_dx_date]                     DATE           NULL,
    [OtherPsychoses_dx]                   INT            NULL,
    [OtherPsychoses_dx_date]              DATE           NULL,
    [PCFutureAppt_DateTime]               DATETIME2 (0)  NULL,
    [PCFutureAppt_PrimaryStopCode]        VARCHAR (5)    NULL,
    [PCFutureAppt_PrimaryStopCodeName]    VARCHAR (100)  NULL,
    [PCFutureAppt_ChecklistID]            NVARCHAR (100) NULL,
    [PCFutureAppt_Facility]               NVARCHAR (100) NULL,
    [PCFutureAppt_ClinicName]             VARCHAR (100)  NULL,
    [MHFutureAppt_DateTime]               DATETIME2 (0)  NULL,
    [MHFutureAppt_PrimaryStopCode]        VARCHAR (5)    NULL,
    [MHFutureAppt_PrimaryStopCodeName]    VARCHAR (100)  NULL,
    [MHFutureAppt_SecondaryStopCode]      VARCHAR (5)    NULL,
    [MHFutureAppt_SecondaryStopCodeName]  VARCHAR (50)   NULL,
    [MHFutureAppt_ChecklistID]            NVARCHAR (100) NULL,
    [MHFutureAppt_Facility]               NVARCHAR (100) NULL,
    [MHFutureAppt_ClinicName]             VARCHAR (100)  NULL,
    [MHFutureAppt_SecondaryOnly]          INT            NULL,
    [OtherFutureAppt_DateTime]            DATETIME2 (0)  NULL,
    [OtherFutureAppt_PrimaryStopCode]     VARCHAR (5)    NULL,
    [OtherFutureAppt_PrimaryStopCodeName] VARCHAR (100)  NULL,
    [OtherFutureAppt_ChecklistID]         NVARCHAR (100) NULL,
    [OtherFutureAppt_Facility]            NVARCHAR (100) NULL,
    [OtherFutureAppt_ClinicName]          VARCHAR (100)  NULL,
    [OtherFutureAppt_MH_under10min]       INT            NULL,
    [AnyFutureAppt_DateTime]              DATETIME2 (0)  NULL,
    [AnyFutureAppt_PrimaryStopCode]       VARCHAR (5)    NULL,
    [AnyFutureAppt_PrimaryStopCodeName]   VARCHAR (100)  NULL,
    [AnyFutureAppt_SecondaryStopCode]     VARCHAR (5)    NULL,
    [AnyFutureAppt_SecondaryStopCodeName] VARCHAR (50)   NULL,
    [AnyFutureAppt_ChecklistID]           NVARCHAR (100) NULL,
    [AnyFutureAppt_Facility]              NVARCHAR (100) NULL,
    [AnyFutureAppt_ClinicName]            VARCHAR (100)  NULL,
    [PCRecentEnc_VisitDate]               DATETIME2 (3)  NULL,
    [PCRecentEnc_PrimaryStopCode]         VARCHAR (5)    NULL,
    [PCRecentEnc_PrimaryStopCodeName]     VARCHAR (100)  NULL,
    [PCRecentEnc_ChecklistID]             NVARCHAR (10)  NULL,
    [PCRecentEnc_Facility]                NVARCHAR (100) NULL,
    [PCRecentEnc_ClinicName]              VARCHAR (100)  NULL,
    [PCRecentEnc_Provider]                VARCHAR (200)  NULL,
    [MHRecentEnc_VisitDate]               DATETIME2 (3)  NULL,
    [MHRecentEnc_PrimaryStopCode]         VARCHAR (5)    NULL,
    [MHRecentEnc_PrimaryStopCodeName]     VARCHAR (100)  NULL,
    [MHRecentEnc_SecondaryStopCode]       VARCHAR (5)    NULL,
    [MHRecentEnc_SecondaryStopCodeName]   VARCHAR (100)  NULL,
    [MHRecentEnc_ChecklistID]             NVARCHAR (10)  NULL,
    [MHRecentEnc_Facility]                NVARCHAR (100) NULL,
    [MHRecentEnc_ClinicName]              VARCHAR (100)  NULL,
    [MHRecentEnc_Provider]                VARCHAR (200)  NULL,
    [MHRecentEnc_SecondaryOnly]           INT            NULL,
    [EDRecentEnc_VisitDate]               DATETIME2 (3)  NULL,
    [EDRecentEnc_PrimaryStopCode]         VARCHAR (5)    NULL,
    [EDRecentEnc_PrimaryStopCodeName]     VARCHAR (100)  NULL,
    [EDRecentEnc_ChecklistID]             NVARCHAR (10)  NULL,
    [EDRecentEnc_Facility]                NVARCHAR (100) NULL,
    [EDRecentEnc_ClinicName]              VARCHAR (100)  NULL,
    [EDRecentEnc_Provider]                VARCHAR (200)  NULL,
    [OtherRecentEnc_VisitDate]            DATETIME2 (3)  NULL,
    [OtherRecentEnc_PrimaryStopCode]      VARCHAR (5)    NULL,
    [OtherRecentEnc_PrimaryStopCodeName]  VARCHAR (100)  NULL,
    [OtherRecentEnc_ChecklistID]          NVARCHAR (10)  NULL,
    [OtherRecentEnc_Facility]             NVARCHAR (100) NULL,
    [OtherRecentEnc_ClinicName]           VARCHAR (100)  NULL,
    [OtherRecentEnc_Provider]             VARCHAR (200)  NULL,
    [OtherRecentEnc_MH_under10min]        INT            NULL,
    [AnyRecentEnc_VisitDate]              DATETIME2 (3)  NULL,
    [AnyRecentEnc_PrimaryStopCode]        VARCHAR (5)    NULL,
    [AnyRecentEnc_PrimaryStopCodeName]    VARCHAR (100)  NULL,
    [AnyRecentEnc_SecondaryStopCode]      VARCHAR (5)    NULL,
    [AnyRecentEnc_SecondaryStopCodeName]  VARCHAR (100)  NULL,
    [AnyRecentEnc_ChecklistID]            NVARCHAR (10)  NULL,
    [AnyRecentEnc_Facility]               NVARCHAR (100) NULL,
    [AnyRecentEnc_ClinicName]             VARCHAR (100)  NULL,
    [AnyRecentEnc_Provider]               VARCHAR (200)  NULL,
    [PC_Engagement]                       INT            NULL,
    [MH_Engagement]                       INT            NULL,
    [Other_Engagement]                    INT            NULL,
    [Color_Coding]                        INT            NULL,
    [IPAdmit_Date]                        DATETIME2 (0)  NULL,
    [IPDischarge_Date]                    DATETIME2 (0)  NULL,
    [CurrentlyAdmitted]                   INT            NULL,
    [IPDischarge_ChecklistID]             VARCHAR (5)    NULL,
    [IPDischarge_Facility]                NVARCHAR (100) NULL,
    [IPDischarge_Bedsection]              VARCHAR (100)  NULL,
    [ED_counts_pastyear]                  INT            NULL,
    [MH_counts_pastyear]                  INT            NULL,
    [ICMHR_counts_90day]                  INT            NULL,
    [IP_MH_counts_pastyear]               INT            NULL,
    [PCP_Name]                            VARCHAR (100)  NULL,
    [PCP_ChecklistID]                     NVARCHAR (30)  NULL,
    [PCP_Facility]                        NVARCHAR (100) NULL,
    [MHTC_Name]                           VARCHAR (100)  NULL,
    [MHTC_ChecklistID]                    NVARCHAR (30)  NULL,
    [MHTC_Facility]                       NVARCHAR (100) NULL,
    [HRF_ChecklistID]                     VARCHAR (5)    NULL,
    [HRF_Facility]                        NVARCHAR (100) NULL,
    [HRF_Date]                            DATETIME2 (0)  NULL,
    [HRF_Status]                          VARCHAR (32)   NULL,
    [RxTransitions_Antidepressant]        INT            NULL,
    [RxTransitions_Antipsychotic]         INT            NULL,
    [RxTransitions_Benzodiazepine]        INT            NULL,
    [RxTransitions_MoodStabilizer]        INT            NULL,
    [RxTransitions_OpioidAgonist]         INT            NULL,
    [RxTransitions_OpioidForPain]         INT            NULL,
    [RxTransitions_OtherControlledSub]    INT            NULL,
    [RxTransitions_Sedative_zdrug]        INT            NULL,
    [RxTransitions_Stimulant]             INT            NULL,
    [RxTransitions_Antidepressant_Pr]     VARCHAR (100)  NULL,
    [RxTransitions_Antipsychotic_Pr]      VARCHAR (100)  NULL,
    [RxTransitions_Benzodiazepine_Pr]     VARCHAR (100)  NULL,
    [RxTransitions_MoodStabilizer_Pr]     VARCHAR (100)  NULL,
    [RxTransitions_OpioidAgonist_Pr]      VARCHAR (100)  NULL,
    [RxTransitions_OpioidForPain_Pr]      VARCHAR (100)  NULL,
    [RxTransitions_OtherControlledSub_Pr] VARCHAR (100)  NULL,
    [RxTransitions_Sedative_zdrug_Pr]     VARCHAR (100)  NULL,
    [RxTransitions_Stimulant_Pr]          VARCHAR (100)  NULL,
    [RxTransitions_MinDaysForSorting]     INT            NULL
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCIX_PatientReport]
    ON [SMI].[PatientReport];

