CREATE TABLE [Pharm].[LithiumPatientReport] (
    [sta3n]                          NVARCHAR (3)    NULL,
    [Patienticn]                     VARCHAR (50)    NULL,
    [patientsid]                     INT             NULL,
    [maxlabdate]                     DATETIME2 (0)   NULL,
    [PrescriberSID]                  INT             NULL,
    [PrescriberName]                 VARCHAR (100)   NULL,
    [sta6a]                          VARCHAR (50)    NULL,
    [DivisionName]                   VARCHAR (100)   NULL,
    [IntegratedSta3n]                NVARCHAR (30)   NOT NULL,
    [checklistID]                    NVARCHAR (30)   NOT NULL,
    [FollowUpKey]                    INT             NOT NULL,
    [PCFutureAppointmentDateTime]    DATETIME2 (0)   NULL,
    [PCFuturePrimaryStopCode]        VARCHAR (5)     NULL,
    [PCFutureStopCodeName]           VARCHAR (100)   NULL,
    [PCFutureAppLocationName]        VARCHAR (50)    NULL,
    [MHFutureAppointmentDateTime]    DATETIME2 (0)   NULL,
    [MHFuturePrimaryStopCode]        VARCHAR (5)     NULL,
    [MHFutureStopCodeName]           VARCHAR (100)   NULL,
    [MHFutureAppLocationName]        VARCHAR (50)    NULL,
    [OtherFutureAppointmentDateTime] DATETIME2 (0)   NULL,
    [OtherFuturePrimaryStopCode]     VARCHAR (5)     NULL,
    [OtherFutureStopCodeName]        VARCHAR (100)   NULL,
    [PatientName]                    VARCHAR (123)   NULL,
    [PatientSSN]                     VARCHAR (50)    NULL,
    [LastFour]                       VARCHAR (4)     NULL,
    [Age]                            NUMERIC (18)    NULL,
    [Gender]                         CHAR (1)        NULL,
    [LookUpLastFour]                 VARCHAR (104)   NULL,
    [PrimaryCareProvider]            VARCHAR (100)   NULL,
    [PrimaryProviderSID]             INT             NULL,
    [PrimaryProviderInstitution]     VARCHAR (50)    NULL,
    [PrimaryProviderDivision]        VARCHAR (100)   NULL,
    [MHTC]                           VARCHAR (102)   NULL,
    [MHTCType]                       VARCHAR (100)   NULL,
    [MHTCInstitutionCode]            VARCHAR (50)    NULL,
    [MHTCInstitutionName]            NVARCHAR (712)  NULL,
    [drug]                           VARCHAR (100)   NULL,
    [MonthsInTreatment]              INT             NULL,
    [PresentReleaseTime]             DATETIME2 (0)   NULL,
    [HealthFactorType]               VARCHAR (40)    NULL,
    [HealthFactorDateTime]           DATETIME2 (0)   NULL,
    [labchemtestname]                VARCHAR (50)    NULL,
    [LabChemResultNumericValue]      DECIMAL (19, 4) NULL,
    [LabChemResultValue]             VARCHAR (100)   NULL,
    [LabChemResultValue_Numeric]     VARCHAR (8000)  NULL,
    [Orderstartdatetime]             SMALLDATETIME   NULL,
    [orderstatus]                    VARCHAR (50)    NULL,
    [MVIPersonSID]                   INT             NULL
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCIX_LithiumPatientReport]
    ON [Pharm].[LithiumPatientReport];

