CREATE TABLE [SUD].[TobaccoUD] (
    [MVIPersonSID]                     INT            NULL,
    [PatientICN]                       VARCHAR (50)   NULL,
    [TobaccoScreenDateTime]            DATETIME2 (0)  NULL,
    [TobaccoScreenType]                VARCHAR (601)  NULL,
    [TobaccoScreen_Past60Days]         INT            NULL,
    [TobaccoScreen_ChecklistID]        NVARCHAR (30)  NULL,
    [TobaccoScreen_Facility]           NVARCHAR (100) NULL,
    [HF_Counsel]                       VARCHAR (3)    NULL,
    [HF_Med]                           VARCHAR (22)   NULL,
    [HF_sorting]                       INT            NULL,
    [Homestation_VISN]                 INT            NULL,
    [Homestation_ChecklistID]          NVARCHAR (30)  NULL,
    [Homestation_Facility]             NVARCHAR (100) NULL,
    [PatientName]                      VARCHAR (200)  NULL,
    [PatientGender]                    VARCHAR (50)   NULL,
    [PatientAge]                       INT            NULL,
    [LastFour]                         CHAR (4)       NULL,
    [DateOfBirth]                      DATE           NULL,
    [Veteran]                          BIT            NULL,
    [PhoneNumber]                      VARCHAR (50)   NULL,
    [StreetAddress1]                   VARCHAR (100)  NULL,
    [StreetAddress2]                   VARCHAR (100)  NULL,
    [City]                             VARCHAR (100)  NULL,
    [State]                            VARCHAR (22)   NULL,
    [Zip]                              VARCHAR (5)    NULL,
    [TotalMHEnc]                       INT            NULL,
    [HF_staffsid1]                     INT            NULL,
    [HF_staff1]                        VARCHAR (100)  NULL,
    [HF_staff_datetime1]               DATETIME2 (0)  NULL,
    [HF_staffsid2]                     INT            NULL,
    [HF_staff2]                        VARCHAR (100)  NULL,
    [HF_staff_datetime2]               DATETIME2 (0)  NULL,
    [HF_IntakeNeeded]                  VARCHAR (5)    NULL,
    [HF_IntakeAttempt1]                VARCHAR (50)   NULL,
    [HF_IntakeAttempt1_date]           DATETIME2 (0)  NULL,
    [HF_IntakeAttempt2]                VARCHAR (50)   NULL,
    [HF_IntakeAttempt2_date]           DATETIME2 (0)  NULL,
    [HF_IntakeAttempt3]                VARCHAR (50)   NULL,
    [HF_IntakeAttempt3_date]           DATETIME2 (0)  NULL,
    [HF_FollowUpNeeded]                VARCHAR (5)    NULL,
    [HF_FollowUpAttempt1]              VARCHAR (50)   NULL,
    [HF_FollowUpAttempt1_date]         DATETIME2 (0)  NULL,
    [HF_FollowUpAttempt2]              VARCHAR (50)   NULL,
    [HF_FollowUpAttempt2_date]         DATETIME2 (0)  NULL,
    [HF_FollowUpAttempt3]              VARCHAR (50)   NULL,
    [HF_FollowUpAttempt3_date]         DATETIME2 (0)  NULL,
    [HF_CaseClosed]                    VARCHAR (5)    NULL,
    [HF_CaseClosed_MostRecentDateTime] DATETIME2 (0)  NULL,
    [HF_CaseClosed_HealthFactorType]   VARCHAR (50)   NULL,
    [HF_CaseClosedStaff]               VARCHAR (100)  NULL,
    [HF_RecentCase_Outcome]            VARCHAR (100)  NULL,
    [CaseReopened]                     BIT            NULL,
    [CaseStatus]                       INT            NULL,
    [DaysSinceLastCall]                INT            NULL,
    [OutreachNeeded]                   INT            NULL,
    [ENDS_OtherProducts]               VARCHAR (50)   NULL,
    [Bup_DrugName]                     VARCHAR (100)  NULL,
    [Bup_ReleaseDate]                  DATETIME2 (0)  NULL,
    [Bup_RxStatus]                     VARCHAR (50)   NULL,
    [Bup_ChecklistID]                  VARCHAR (5)    NULL,
    [NicotineGum_DrugName]             VARCHAR (100)  NULL,
    [NicotineGum_ReleaseDate]          DATETIME2 (0)  NULL,
    [NicotineGum_RxStatus]             VARCHAR (50)   NULL,
    [NicotineGum_ChecklistID]          VARCHAR (5)    NULL,
    [NicotinePatch_DrugName]           VARCHAR (100)  NULL,
    [NicotinePatch_ReleaseDate]        DATETIME2 (0)  NULL,
    [NicotinePatch_RxStatus]           VARCHAR (50)   NULL,
    [NicotinePatch_ChecklistID]        VARCHAR (5)    NULL,
    [NicotineLozenge_DrugName]         VARCHAR (100)  NULL,
    [NicotineLozenge_ReleaseDate]      DATETIME2 (0)  NULL,
    [NicotineLozenge_RxStatus]         VARCHAR (50)   NULL,
    [NicotineLozenge_ChecklistID]      VARCHAR (5)    NULL,
    [NicotineSpray_DrugName]           VARCHAR (100)  NULL,
    [NicotineSpray_ReleaseDate]        DATETIME2 (0)  NULL,
    [NicotineSpray_RxStatus]           VARCHAR (50)   NULL,
    [NicotineSpray_ChecklistID]        VARCHAR (5)    NULL,
    [Varenicline_DrugName]             VARCHAR (100)  NULL,
    [Varenicline_ReleaseDate]          DATETIME2 (0)  NULL,
    [Varenicline_RxStatus]             VARCHAR (50)   NULL,
    [Varenicline_ChecklistID]          VARCHAR (5)    NULL,
    [MostRecentTxDate_sorting]         DATETIME2 (0)  NULL,
    [ActiveTobaccoTx]                  INT            NULL,
    [AnyTobaccoTx_60days]              INT            NULL,
    [PCP_Name]                         VARCHAR (100)  NULL,
    [PCP_ChecklistID]                  NVARCHAR (30)  NULL,
    [PCP_Facility]                     NVARCHAR (100) NULL,
    [MHTC_Name]                        VARCHAR (100)  NULL,
    [MHTC_ChecklistID]                 NVARCHAR (30)  NULL,
    [MHTC_Facility]                    NVARCHAR (100) NULL,
    [Provider_Sorting]                 VARCHAR (100)  NULL,
    [PCRecent_VisitDateTime]           DATETIME2 (0)  NULL,
    [PCRecent_StopCode]                VARCHAR (5)    NULL,
    [PCRecent_StopCodeName]            VARCHAR (100)  NULL,
    [PCRecent_ChecklistID]             VARCHAR (5)    NULL,
    [PCRecent_Facility]                NVARCHAR (100) NULL,
    [MHRecent_VisitDateTime]           DATETIME2 (0)  NULL,
    [MHRecent_StopCode]                VARCHAR (5)    NULL,
    [MHRecent_StopCodeName]            VARCHAR (100)  NULL,
    [MHRecent_ChecklistID]             VARCHAR (5)    NULL,
    [MHRecent_Facility]                NVARCHAR (100) NULL,
    [RecentEnc_Sorting]                DATETIME2 (0)  NULL,
    [PCAppt_VisitDateTime]             DATETIME2 (0)  NULL,
    [PCAppt_StopCode]                  VARCHAR (5)    NULL,
    [PCAppt_StopCodeName]              VARCHAR (100)  NULL,
    [PCAppt_ChecklistID]               VARCHAR (5)    NULL,
    [PCAppt_Facility]                  NVARCHAR (100) NULL,
    [MHAppt_VisitDateTime]             DATETIME2 (0)  NULL,
    [MHAppt_StopCode]                  VARCHAR (5)    NULL,
    [MHAppt_StopCodeName]              VARCHAR (100)  NULL,
    [MHAppt_ChecklistID]               VARCHAR (5)    NULL,
    [MHAppt_Facility]                  NVARCHAR (100) NULL,
    [NextAppt_Sorting]                 DATETIME2 (0)  NULL,
    [TobaccoCounseling_VisitDateTime]  DATETIME2 (0)  NULL,
    [MH_Diagnosis]                     VARCHAR (500)  NULL,
    [SUD_Diagnosis]                    VARCHAR (500)  NULL,
    [HRF_Date]                         DATETIME2 (0)  NULL,
    [HRF_Status]                       VARCHAR (32)   NULL
);




















GO
