CREATE TABLE [SBOSR].[SDVDetails_PBI] (
    [MVIPersonSID]          INT            NULL,
    [PatientICN]            NVARCHAR (50)  NULL,
    [SPANPatientID]         INT            NULL,
    [ActivePatient]         NVARCHAR (20)  NULL,
    [PatientKey]            NVARCHAR (100) NOT NULL,
    [PatientNameLastFour]   VARCHAR (100)  NULL,
    [ChecklistID]           NVARCHAR (100) NULL,
    [ADMPARENT_FCDM]        NVARCHAR (100) NULL,
    [Facility]              NVARCHAR (100) NULL,
    [SDVCntType]            NVARCHAR (10)  NULL,
    [SDVCtnKey]             VARCHAR (MAX)  NULL,
    [EventType]             NVARCHAR (20)  NULL,
    [EventCountIndicator]   NVARCHAR (25)  NULL,
    [Date]                  DATE           NULL,
    [DataSource]            VARCHAR (55)   NULL,
    [Month]                 NVARCHAR (3)   NULL,
    [MonthName]             NVARCHAR (10)  NULL,
    [Year]                  NVARCHAR (10)  NULL,
    [EventDate]             VARCHAR (MAX)  NULL,
    [EventDateCombined]     VARCHAR (MAX)  NULL,
    [EventDateNULL]         INT            NULL,
    [ReportDate]            DATE           NULL,
    [E_EventDateT]          NVARCHAR (10)  NULL,
    [E_ReportDateT]         NVARCHAR (10)  NULL,
    [R_EventDateT]          NVARCHAR (10)  NULL,
    [R_ReportDateT]         NVARCHAR (10)  NULL,
    [SDVClassification]     NVARCHAR (100) NULL,
    [Seen7Days]             NVARCHAR (5)   NULL,
    [Seen30Days]            NVARCHAR (5)   NULL,
    [VAProperty]            NVARCHAR (10)  NULL,
    [SevenDaysDx]           NVARCHAR (10)  NULL,
    [MethodForVisuals]      NVARCHAR (25)  NULL,
    [MethodNumber]          NVARCHAR (15)  NULL,
    [Method1=Method2]       INT            NULL,
    [Method1=Method3]       INT            NULL,
    [Method2=Method3]       INT            NULL,
    [Method1]               VARCHAR (255)  NULL,
    [Method2]               VARCHAR (255)  NULL,
    [Method3]               VARCHAR (255)  NULL,
    [Outcome]               NVARCHAR (MAX) NULL,
    [Overdose]              INT            NULL,
    [FatalvNonFatal]        NVARCHAR (10)  NULL,
    [BHAP_FITC_DueDate]     DATE           NULL,
    [Fatal]                 INT            NULL,
    [PreparatoryBehavior]   INT            NULL,
    [UndeterminedSDV]       INT            NULL,
    [SuicidalSDV]           INT            NULL,
    [HRFType]               NVARCHAR (50)  NULL,
    [MedType]               NVARCHAR (50)  NULL,
    [RV_Status]             NVARCHAR (50)  NULL,
    [RV_Status_Number]      INT            NULL,
    [HRFNumber]             INT            NULL,
    [Month_Number]          NVARCHAR (10)  NULL,
    [MethodPrintName]       VARCHAR (MAX)  NULL,
    [MonthYear]             NVARCHAR (10)  NULL,
    [AdmitYearMonth_Number] NVARCHAR (10)  NULL
);

