CREATE TABLE [ORM].[PatientOTRRView] (
    [MVIPersonSID]              INT              NOT NULL,
    [PatientICN]                VARCHAR (50)     NULL,
    [ChecklistID]               NVARCHAR (30)    NULL,
    [Sta3n]                     SMALLINT         NULL,
    [VISN]                      INT              NULL,
    [Facility]                  NVARCHAR (510)   NULL,
    [PatientName]               VARCHAR (200)    NULL,
    [LastFour]                  CHAR (4)         NULL,
    [DateOfBirth]               DATE             NULL,
    [Age]                       INT              NULL,
    [Gender]                    CHAR (1)         NULL,
    [MEDD30d]                   NUMERIC (10, 1)  NULL,
    [OpioidForPain_Rx]          SMALLINT         NULL,
    [Benzodiazepine_Rx]         SMALLINT         NOT NULL,
    [SedatingPainORM_Rx]        SMALLINT         NOT NULL,
    [MOUD]                      INT              NULL,
    [TramadolOnly]              SMALLINT         NOT NULL,
    [riosordscore]              INT              NULL,
    [riosordriskclass]          INT              NULL,
    [RiskCategory]              INT              NOT NULL,
    [RiskCategorylabel]         VARCHAR (120)    NOT NULL,
    [RiskScore]                 DECIMAL (38, 15) NULL,
    [RiskMitScore]              INT              NULL,
    [PatientRecordFlag_Suicide] BIT              NOT NULL,
    [UDSDate]                   DATE             NULL,
    [DaysSinceUDS]              INT              NULL,
    [ConsentDate]               DATETIME2 (7)    NULL,
    [DaysSinceConsent]          INT              NULL,
    [PDMPDate]                  DATETIME2 (7)    NULL,
    [DaysSincePDMP]             INT              NULL,
    [ChronicOpioid]             INT              NULL,
    [NaloxoneContext]           VARCHAR (60)     NULL,
    [NaloxoneDate]              DATE             NULL,
    [SafetyPlanContext]         VARCHAR (60)     NULL,
    [SafetyPlanDate]            DATE             NULL,
    [ApptDateTime_PC]           DATETIME2 (0)    NULL,
    [ApptLocation_PC]           NVARCHAR (255)   NULL,
    [ApptStop_PC]               VARCHAR (100)    NULL,
    [ApptDateTime_MH]           DATETIME2 (0)    NULL,
    [ApptLocation_MH]           NVARCHAR (255)   NULL,
    [ApptStop_MH]               VARCHAR (100)    NULL,
    [PCP]                       VARCHAR (202)    NULL,
    [PCPsid]                    INT              NULL,
    [MHTC]                      VARCHAR (202)    NULL,
    [MHTCsid]                   INT              NULL,
    [BHIP]                      VARCHAR (100)    NULL,
    [BHIPsid]                   INT              NULL,
    [PACT]                      VARCHAR (100)    NULL,
    [PACTsid]                   INT              NULL,
    [LocalPrescriberSID]        INT              NULL,
    [LocalPrescriber]           VARCHAR (202)    NULL,
    [OtherPrescriber]           VARCHAR (100)    NULL,
    [OtherPrescriberSID]        INT              NULL,
    [OtherPrescriberLocation]   NVARCHAR (30)    NULL,
    [OUD]                       INT              NULL,
    [SUDdx_poss]                INT              NULL,
    [ODPastYear]                BIT              NULL,
    [Hospice]                   INT              NULL,
    [ODdate]                    DATETIME         NULL,
    [ODContext]                 VARCHAR (50)     NULL,
    [PreparatoryBehavior]       FLOAT (53)       NULL,
    [CCP]                       VARCHAR (100)    NULL,
    [CCPsid]                    INT              NULL
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCIX_PatientOTRRView]
    ON [ORM].[PatientOTRRView];

