CREATE TABLE [ORM].[RiskScore] (
    [MVIPersonSID]                        INT              NOT NULL,
    [STA3N]                               SMALLINT         NULL,
    [VISN]                                SMALLINT         NULL,
    [Gender]                              VARCHAR (100)    NULL,
    [Age]                                 INT              NULL,
    [GenderMale]                          SMALLINT         NULL,
    [GenderFemale]                        SMALLINT         NULL,
    [Age30]                               SMALLINT         NULL,
    [Age3150]                             SMALLINT         NULL,
    [Age5165]                             SMALLINT         NULL,
    [Age66]                               SMALLINT         NULL,
    [EH_AIDS]                             SMALLINT         NULL,
    [EH_CHRNPULM]                         SMALLINT         NULL,
    [EH_COMDIAB]                          SMALLINT         NULL,
    [EH_ELECTRLYTE]                       SMALLINT         NULL,
    [EH_HYPERTENS]                        SMALLINT         NULL,
    [EH_LIVER]                            SMALLINT         NULL,
    [EH_NMETTUMR]                         SMALLINT         NULL,
    [EH_OTHNEURO]                         SMALLINT         NULL,
    [EH_PARALYSIS]                        SMALLINT         NULL,
    [EH_PEPTICULC]                        SMALLINT         NULL,
    [EH_PERIVALV]                         SMALLINT         NULL,
    [EH_RENAL]                            SMALLINT         NULL,
    [EH_HEART]                            SMALLINT         NULL,
    [EH_ARRHYTH]                          SMALLINT         NULL,
    [EH_VALVDIS]                          SMALLINT         NULL,
    [EH_PULMCIRC]                         SMALLINT         NULL,
    [EH_HYPOTHY]                          SMALLINT         NULL,
    [EH_RHEUMART]                         SMALLINT         NULL,
    [EH_COAG]                             SMALLINT         NULL,
    [EH_WEIGHTLS]                         SMALLINT         NULL,
    [EH_DefANEMIA]                        SMALLINT         NULL,
    [SedateIssue]                         SMALLINT         NULL,
    [AUD_ORM]                             SMALLINT         NULL,
    [OUD]                                 SMALLINT         NULL,
    [SUDdx_poss]                          SMALLINT         NULL,
    [OpioidOverdose]                      SMALLINT         NULL,
    [SAE_Falls]                           SMALLINT         NULL,
    [SAE_OtherAccident]                   SMALLINT         NULL,
    [SAE_OtherDrug]                       SMALLINT         NULL,
    [SAE_Vehicle]                         SMALLINT         NULL,
    [Suicide]                             SMALLINT         NULL,
    [SAE_sed]                             SMALLINT         NULL,
    [SAE_acet]                            SMALLINT         NULL,
    [Overdose_Suicide]                    SMALLINT         NULL,
    [AnySAE]                              SMALLINT         NULL,
    [Other_MH_STORM]                      SMALLINT         NULL,
    [SUD_NoOUD_NoAUD]                     SMALLINT         NULL,
    [BIPOLAR]                             SMALLINT         NULL,
    [PTSD]                                SMALLINT         NULL,
    [MDD]                                 SMALLINT         NULL,
    [OtherSUD_RiskModel]                  SMALLINT         NULL,
    [SedativeUseDisorder]                 SMALLINT         NULL,
    [CannabisUD_HallucUD]                 SMALLINT         NULL,
    [CocaineUD_AmphUD]                    SMALLINT         NULL,
    [EH_UNCDIAB]                          SMALLINT         NULL,
    [EH_LYMPHOMA]                         SMALLINT         NULL,
    [EH_METCANCR]                         SMALLINT         NULL,
    [EH_OBESITY]                          SMALLINT         NULL,
    [EH_BLANEMIA]                         SMALLINT         NULL,
    [SumOverdose_Suicide]                 BIGINT           NULL,
    [Osteoporosis]                        SMALLINT         NULL,
    [SleepApnea]                          SMALLINT         NULL,
    [NicDx_Poss]                          SMALLINT         NULL,
    [COCNdx]                              SMALLINT         NULL,
    [Detox_CPT]                           SMALLINT         NULL,
    [MHOutpat]                            SMALLINT         NULL,
    [MHInpat]                             SMALLINT         NULL,
    [ERvisit]                             SMALLINT         NULL,
    [PainAdjAnticonvulsant_Rx]            SMALLINT         NULL,
    [PainAdjSNRI_Rx]                      SMALLINT         NULL,
    [PainAdjTCA_Rx]                       SMALLINT         NULL,
    [Sum_Painadj]                         BIGINT           NULL,
    [SedativeOpioid_Rx]                   SMALLINT         NULL,
    [TotalMEDD]                           DECIMAL (38, 15) NULL,
    [MEDD_Report]                         DECIMAL (38, 15) NULL,
    [TramadolOnly]                        SMALLINT         NULL,
    [ChronicShortActing]                  SMALLINT         NULL,
    [LongActing]                          SMALLINT         NULL,
    [NonChronicShortActing]               SMALLINT         NULL,
    [MostRecentPrescriber]                VARCHAR (100)    NULL,
    [MostRecentPrescriberSID]             VARCHAR (25)     NULL,
    [Hospice]                             SMALLINT         NULL,
    [Bowel_Rx]                            SMALLINT         NULL,
    [Anxiolytics_Rx]                      SMALLINT         NULL,
    [InteractionOverdoseOtherAE]          SMALLINT         NULL,
    [InteractionOverdoseMHInpat]          SMALLINT         NULL,
    [InteractionOverdoseOUD]              SMALLINT         NULL,
    [InteractionOUDAnySAE]                SMALLINT         NULL,
    [InteractionOUDMHInpat]               SMALLINT         NULL,
    [InteractionAnySAEMHInpat]            SMALLINT         NULL,
    [RiskScore]                           DECIMAL (38, 15) NULL,
    [RiskScore10]                         DECIMAL (38, 15) NULL,
    [RiskScore50]                         DECIMAL (38, 15) NULL,
    [RiskScoreNoSed]                      DECIMAL (38, 15) NULL,
    [RiskScoreAny]                        DECIMAL (38, 15) NULL,
    [RiskScoreAny10]                      DECIMAL (38, 15) NULL,
    [RiskScoreAny50]                      DECIMAL (38, 15) NULL,
    [RiskScoreAnyNoSed]                   DECIMAL (38, 15) NULL,
    [RiskScoreAnyHypothetical10]          DECIMAL (38, 15) NULL,
    [RiskScoreAnyHypothetical50]          DECIMAL (38, 15) NULL,
    [RiskScoreAnyHypothetical90]          DECIMAL (38, 15) NULL,
    [RiskScoreHypothetical10]             DECIMAL (38, 15) NULL,
    [RiskScoreHypothetical50]             DECIMAL (38, 15) NULL,
    [RiskScoreHypothetical90]             DECIMAL (38, 15) NULL,
    [RiskCategory]                        INT              NULL,
    [RiskAnyCategory]                     INT              NULL,
    [RiskCategory_Hypothetical90]         INT              NULL,
    [RiskCategory_Hypothetical50]         INT              NULL,
    [RiskCategory_Hypothetical10]         INT              NULL,
    [RiskAnyCategory_Hypothetical90]      INT              NULL,
    [RiskAnyCategory_Hypothetical50]      INT              NULL,
    [RiskAnyCategory_Hypothetical10]      INT              NULL,
    [RiskAnyCategoryLabel]                VARCHAR (50)     NULL,
    [RiskCategoryLabel]                   VARCHAR (50)     NULL,
    [RiskCategoryLabel_Hypothetical90]    VARCHAR (50)     NULL,
    [RiskCategoryLabel_Hypothetical50]    VARCHAR (50)     NULL,
    [RiskCategorylabel_Hypothetical10]    VARCHAR (50)     NULL,
    [RiskAnyCategoryLabel_Hypothetical90] VARCHAR (50)     NULL,
    [RiskAnyCategoryLabel_Hypothetical50] VARCHAR (50)     NULL,
    [RiskAnyCategorylabel_Hypothetical10] VARCHAR (50)     NULL
);


GO
CREATE CLUSTERED INDEX [ORM_RiskScore_MVIPersonSID]
    ON [ORM].[RiskScore]([MVIPersonSID] ASC) WITH (FILLFACTOR = 100);

