CREATE TABLE [OMHSP_Standard].[SBOR] (
    [MVIPersonSID]              INT           NOT NULL,
    [Sta3n]                     INT           NULL,
    [ChecklistID]               VARCHAR (5)   NULL,
    [VisitSID]                  BIGINT        NULL,
    [DocFormActivitySID]        BIGINT        NULL,
    [EntryDateTime]             DATETIME      NULL,
    [HealthFactorDateTime]      DATETIME      NULL,
    [TIUDocumentDefinition]     VARCHAR (100) NULL,
    [EventCategory]             VARCHAR (20)  NULL,
    [EventDate]                 VARCHAR (MAX) NULL,
    [EventDateFormatted]        DATE          NULL,
    [Year]                      SMALLINT      NULL,
    [EventType]                 VARCHAR (50)  NULL,
    [Setting]                   VARCHAR (80)  NULL,
    [SettingComments]           VARCHAR (MAX) NULL,
    [SDVClassification]         VARCHAR (100) NULL,
    [VAProperty]                VARCHAR (7)   NULL,
    [SevenDaysDx]               VARCHAR (7)   NULL,
    [Preparatory]               VARCHAR (7)   NULL,
    [Interrupted]               VARCHAR (15)  NULL,
    [InterruptedComments]       VARCHAR (MAX) NULL,
    [Injury]                    VARCHAR (7)   NULL,
    [InjuryComments]            VARCHAR (MAX) NULL,
    [Outcome1]                  VARCHAR (50)  NULL,
    [Outcome1Comments]          VARCHAR (MAX) NULL,
    [Outcome2]                  VARCHAR (50)  NULL,
    [Outcome2Comments]          VARCHAR (MAX) NULL,
    [MethodType1]               VARCHAR (55)  NULL,
    [Method1]                   VARCHAR (55)  NULL,
    [MethodComments1]           VARCHAR (MAX) NULL,
    [MethodType2]               VARCHAR (55)  NULL,
    [Method2]                   VARCHAR (55)  NULL,
    [MethodComments2]           VARCHAR (MAX) NULL,
    [MethodType3]               VARCHAR (55)  NULL,
    [Method3]                   VARCHAR (55)  NULL,
    [MethodComments3]           VARCHAR (MAX) NULL,
    [AdditionalMethodsReported] VARCHAR (3)   NULL,
    [ODProvReview]              BIT           NULL,
    [ODReviewDate]              DATETIME      NULL,
    [DaysBetween]               SMALLINT      NULL
);

