CREATE TABLE [LookUp].[Drug_VUID] (
    [VUID]                            VARCHAR (50)    NOT NULL,
    [DrugNameWithDose]                VARCHAR (200)   NULL,
    [DrugNameWithoutDose]             VARCHAR (100)   NULL,
    [StrengthNumeric]                 DECIMAL (19, 4) NULL,
    [CalculatedStrengthNumeric]       DECIMAL (19, 4) NULL,
    [PrimaryDrugClassCode]            VARCHAR (100)   NULL,
    [DosageForm]                      VARCHAR (100)   NULL,
    [CMOP]                            VARCHAR (50)    NULL,
    [CSFederalSchedule]               VARCHAR (50)    NULL,
    [AchAntiHist_Rx]                  BIT             NULL,
    [AChAD_Rx]                        BIT             NULL,
    [AChALL_Rx]                       BIT             NULL,
    [AlcoholPharmacotherapy_Rx]       BIT             NULL,
    [AlcoholPharmacotherapy_notop_Rx] BIT             NULL,
    [Alprazolam_Rx]                   BIT             NULL,
    [Antidepressant_Rx]               BIT             NULL,
    [SSRI_SNRI_Rx]                    BIT             NULL,
    [Antipsychotic_Geri_Rx]           BIT             NULL,
    [Antipsychotic_Rx]                BIT             NULL,
    [AntipsychoticSecondGen_Rx]       BIT             NULL,
    [Anxiolytics_Rx]                  BIT             NULL,
    [Benzodiazepine_Rx]               BIT             NULL,
    [Bowel_Rx]                        BIT             NULL,
    [Clonazepam_Rx]                   BIT             NULL,
    [Lorazepam_Rx]                    BIT             NULL,
    [Mirtazapine_Rx]                  BIT             NULL,
    [MPRCalculated_Rx]                BIT             NULL,
    [MoodStabilizer_Rx]               BIT             NULL,
    [MoodStabilizer_GE3_Rx]           BIT             NULL,
    [NaltrexoneINJ_Rx]                BIT             NULL,
    [Olanzapine_Rx]                   BIT             NULL,
    [Opioid_Rx]                       BIT             NULL,
    [OpioidAgonist_Rx]                BIT             NULL,
    [PainAdjAnticonvulsant_Rx]        BIT             NULL,
    [PainAdjTCA_Rx]                   BIT             NULL,
    [PainAdjSNRI_Rx]                  BIT             NULL,
    [PDSIRelevant_Rx]                 BIT             NULL,
    [Prazosin_Rx]                     BIT             NULL,
    [Prochlorperazine_Rx]             BIT             NULL,
    [Promethazine_Rx]                 BIT             NULL,
    [Psychotropic_Rx]                 BIT             NULL,
    [Reach_AntiDepressant_Rx]         BIT             NULL,
    [Reach_AntiPsychotic_Rx]          BIT             NULL,
    [Reach_opioid_Rx]                 BIT             NULL,
    [Reach_statin_Rx]                 BIT             NULL,
    [Reach_SedativeAnxiolytic_Rx]     BIT             NULL,
    [SedatingPainORM_Rx]              BIT             NULL,
    [SedativeOpioid_Rx]               BIT             NULL,
    [Sedative_zdrug_Rx]               BIT             NULL,
    [Stimulant_Rx]                    BIT             NULL,
    [StimulantADHD_Rx]                BIT             NULL,
    [TobaccoPharmacotherapy_Rx]       BIT             NULL,
    [Tramadol_Rx]                     BIT             NULL,
    [Zolpidem_Rx]                     BIT             NULL,
    [Methadone_Rx]                    BIT             NULL,
    [OpioidForPain_Rx]                BIT             NULL,
    [NaloxoneKit_Rx]                  BIT             NULL,
    [SSRI_Rx]                         BIT             NULL,
    [ControlledSubstance]             BIT             NULL,
    [CNS_Depress_Rx]                  BIT             NULL,
    [CNS_ActiveMed_Rx]                BIT             NULL,
    PRIMARY KEY CLUSTERED ([VUID] ASC)
);

