CREATE TABLE [LookUp].[ICD10] (
    [ICD10SID]                      BIGINT         NULL,
    [Sta3n]                         SMALLINT       NOT NULL,
    [ICD10Code]                     VARCHAR (100)  NOT NULL,
    [ICD10Description]              VARCHAR (8000) NULL,
    [ALCdx_poss]                    BIT            NULL,
    [AmphetamineUseDisorder]        BIT            NULL,
    [AUD]                           BIT            NULL,
    [AUD_ORM]                       BIT            NULL,
    [Benzo_AD_MHDx]                 BIT            NULL,
    [BIPOLAR]                       BIT            NULL,
    [Cannabis]                      BIT            NULL,
    [CannabisUD_HallucUD]           BIT            NULL,
    [COCNdx]                        BIT            NULL,
    [CocaineUD_AmphUD]              BIT            NULL,
    [DEMENTIA]                      BIT            NULL,
    [DEPRESS]                       BIT            NULL,
    [EH_AIDS]                       BIT            NULL,
    [EH_ARRHYTH]                    BIT            NULL,
    [EH_BLANEMIA]                   BIT            NULL,
    [EH_CHRNPULM]                   BIT            NULL,
    [EH_COAG]                       BIT            NULL,
    [EH_COMDIAB]                    BIT            NULL,
    [EH_DefANEMIA]                  BIT            NULL,
    [EH_ELECTRLYTE]                 BIT            NULL,
    [EH_HEART]                      BIT            NULL,
    [EH_HYPERTENS]                  BIT            NULL,
    [EH_HYPOTHY]                    BIT            NULL,
    [EH_LIVER]                      BIT            NULL,
    [EH_Lymphoma]                   BIT            NULL,
    [EH_METCANCR]                   BIT            NULL,
    [EH_NMETTUMR]                   BIT            NULL,
    [EH_OBESITY]                    BIT            NULL,
    [EH_OTHNEURO]                   BIT            NULL,
    [EH_PARALYSIS]                  BIT            NULL,
    [EH_PEPTICULC]                  BIT            NULL,
    [EH_PERIVALV]                   BIT            NULL,
    [EH_PULMCIRC]                   BIT            NULL,
    [EH_RENAL]                      BIT            NULL,
    [EH_RHEUMART]                   BIT            NULL,
    [EH_SolidTumorNoMet]            BIT            NULL,
    [EH_UNCDIAB]                    BIT            NULL,
    [EH_VALVDIS]                    BIT            NULL,
    [EH_WEIGHTLS]                   BIT            NULL,
    [Homeless]                      BIT            NULL,
    [MDD]                           BIT            NULL,
    [MedIndAntiDepressant]          BIT            NULL,
    [MedIndBenzodiazepine]          BIT            NULL,
    [MHSUDdx_poss]                  BIT            NULL,
    [Nicdx_poss]                    BIT            NULL,
    [OpioidOverdose]                BIT            NULL,
    [Osteoporosis]                  BIT            NULL,
    [OtherMH]                       BIT            NULL,
    [OUD]                           BIT            NULL,
    [Psych]                         BIT            NULL,
    [PTSD]                          BIT            NULL,
    [SAE_Acet]                      BIT            NULL,
    [SAE_Falls]                     BIT            NULL,
    [SAE_OtherAccident]             BIT            NULL,
    [SAE_OtherDrug]                 BIT            NULL,
    [SAE_sed]                       BIT            NULL,
    [SAE_Vehicle]                   BIT            NULL,
    [Schiz]                         BIT            NULL,
    [SedateIssue]                   BIT            NULL,
    [SedativeUseDisorder]           BIT            NULL,
    [SleepApnea]                    BIT            NULL,
    [SMI]                           BIT            NULL,
    [SUD_NoOUD_NoAUD]               BIT            NULL,
    [OtherSUD_RiskModel]            BIT            NULL,
    [SUDdx_poss]                    BIT            NULL,
    [Suicide]                       BIT            NULL,
    [SuicideAttempt]                BIT            NULL,
    [Tourette]                      BIT            NULL,
    [Huntington]                    BIT            NULL,
    [MHorMedInd_AD]                 BIT            NULL,
    [MHorMedInd_Benzo]              BIT            NULL,
    [REACH_attempt]                 BIT            NULL,
    [REACH_arth]                    BIT            NULL,
    [REACH_bipolI]                  BIT            NULL,
    [REACH_ca_head]                 BIT            NULL,
    [REACH_chronic]                 BIT            NULL,
    [REACH_dep]                     BIT            NULL,
    [REACH_dm]                      BIT            NULL,
    [REACH_sle]                     BIT            NULL,
    [REACH_sud]                     BIT            NULL,
    [REACH_othanxdis]               BIT            NULL,
    [REACH_PersonD]                 BIT            NULL,
    [SUD_Active_Dx]                 BIT            NULL,
    [PDE_OverdoseAndPoison]         BIT            NULL,
    [PDE_ExternalCauses]            BIT            NULL,
    [PDE_SuicideRelated]            BIT            NULL,
    [TBI_Dx]                        BIT            NULL,
    [ChronicResp_Dx]                BIT            NULL,
    [Other_MH_STORM]                BIT            NULL,
    [ADD_ADHD]                      BIT            NULL,
    [Narcolepsy]                    BIT            NULL,
    [BingeEating]                   BIT            NULL,
    [Amputation]                    BIT            NULL,
    [AnxietyGeneralized]            BIT            NULL,
    [EatingDisorderUnspecified]     BIT            NULL,
    [IntentionalSelfHarmIdeation]   BIT            NULL,
    [MoodDisorderOther]             BIT            NULL,
    [OtherSpecifiedEatingDisorders] BIT            NULL,
    [PainAbdominal]                 BIT            NULL,
    [PainOther]                     BIT            NULL,
    [PainSystemicDisorder]          BIT            NULL,
    [Parkinsons]                    BIT            NULL,
    [PsychosocialProblemsNOS]       BIT            NULL,
    [PsychoticDisorderOther]        BIT            NULL,
    [ViablePregnancy]               BIT            NULL
);




GO
CREATE CLUSTERED INDEX [CIX_LookUp_ICD10SID]
    ON [LookUp].[ICD10]([ICD10SID] ASC);

