CREATE TABLE [CaringLetters].[HRF_NCOA_BadAddress_DoNotSend] (
    [RECNO]                  INT           NULL,
    [Company]                VARCHAR (20)  NULL,
    [FullName]               VARCHAR (100) NULL,
    [Prefix]                 VARCHAR (10)  NULL,
    [First_Name]             VARCHAR (50)  NULL,
    [Mddlnm]                 VARCHAR (20)  NULL,
    [Last_Name]              VARCHAR (50)  NULL,
    [Suffix1]                VARCHAR (10)  NULL,
    [DeletedStreetAddress1]  VARCHAR (100) NULL,
    [DeletedStreetAddress2]  VARCHAR (100) NULL,
    [DeletedCity]            VARCHAR (100) NULL,
    [DeletedState]           VARCHAR (22)  NULL,
    [DeletedZipCode]         VARCHAR (10)  NULL,
    [RC]                     INT           NULL,
    [FN]                     VARCHAR (10)  NULL,
    [MoveDate]               DATE          NULL,
    [MoveType]               VARCHAR (5)   NULL,
    [DPV]                    VARCHAR (1)   NULL,
    [DPVVACANT]              VARCHAR (1)   NULL,
    [DPVNOSTAT]              VARCHAR (1)   NULL,
    [DPVFN]                  VARCHAR (10)  NULL,
    [OriginalStreetAddress1] VARCHAR (100) NULL,
    [OriginalStreetAddress2] VARCHAR (100) NULL,
    [OriginalCity]           VARCHAR (100) NULL,
    [OriginalState]          VARCHAR (22)  NULL,
    [OriginalZipCode]        VARCHAR (10)  NULL,
    [LetterNumber]           INT           NULL,
    [DataPullDate]           VARCHAR (10)  NULL,
    [MVIPersonSID]           INT           NOT NULL,
    [Country]                VARCHAR (100) NULL
);

