CREATE TABLE [CaringLetters].[VCL_LMS_Trends] (
    [WeekBegin]                 DATE NULL,
    [WeekEnd]                   DATE NULL,
    [DataPullDate]              DATE NULL,
    [TotalOffered]              INT  NULL,
    [Accepted]                  INT  NULL,
    [Refused]                   INT  NULL,
    [DeclinedToAnswer]          INT  NULL,
    [MailingsRequestedCount]    INT  NULL,
    [GunlocksRequested]         INT  NULL,
    [MedEnvelopesRequested]     INT  NULL,
    [MailingsSentCount]         INT  NULL,
    [GunlocksMailed]            INT  NULL,
    [MedEnvelopesMailed]        INT  NULL,
    [RefusalCount]              INT  NULL,
    [Refuse_DontWant]           INT  NULL,
    [Refuse_HaveStorageNotUsed] INT  NULL,
    [Refuse_Defense]            INT  NULL,
    [Refuse_AlreadySecured]     INT  NULL,
    [Refuse_Other]              INT  NULL,
    [Refuse_Unknown]            INT  NULL,
    [Refuse_NotOffered]         INT  NULL,
    [Storage_CableLockVCL]      INT  NULL,
    [Storage_CableLockOther]    INT  NULL,
    [Storage_Disassemble]       INT  NULL,
    [Storage_GunSafe]           INT  NULL,
    [Storage_RemoveFromHome]    INT  NULL,
    [Storage_Other]             INT  NULL
);

