CREATE TABLE [CaringLetters].[VCL_LMS_Cohort] (
    [VCL_ID]                    INT            NOT NULL,
    [MVIPersonSID]              INT            NULL,
    [PatientICN]                VARCHAR (20)   NULL,
    [MailingDate]               DATE           NULL,
    [VCL_Call_Date]             DATE           NULL,
    [VCL_IsVet]                 VARCHAR (5)    NULL,
    [VCL_IsActiveDuty]          VARCHAR (10)   NULL,
    [VCL_VeteranStatus]         SMALLINT       NULL,
    [VCL_MilitaryBranch]        SMALLINT       NULL,
    [AcceptedGunLock]           VARCHAR (25)   NULL,
    [Storage_CableLockVCL]      TINYINT        NULL,
    [Storage_CableLockOther]    TINYINT        NULL,
    [Storage_Disassemble]       TINYINT        NULL,
    [Storage_GunSafe]           TINYINT        NULL,
    [Storage_RemoveFromHome]    TINYINT        NULL,
    [Storage_Other]             TINYINT        NULL,
    [Refuse_DontWant]           TINYINT        NULL,
    [Refuse_HaveStorageNotUsed] TINYINT        NULL,
    [Refuse_Defense]            TINYINT        NULL,
    [Refuse_AlreadySecured]     TINYINT        NULL,
    [Refuse_Other]              TINYINT        NULL,
    [Refuse_Unknown]            TINYINT        NULL,
    [Refuse_NotOffered]         TINYINT        NULL,
    [FirstName]                 VARCHAR (100)  NULL,
    [FullName]                  VARCHAR (255)  NULL,
    [PreferredName]             VARCHAR (100)  NULL,
    [Name_VCL_Vet]              VARCHAR (255)  NULL,
    [Name_VCL_Caller]           VARCHAR (255)  NULL,
    [Name_CDW]                  VARCHAR (255)  NULL,
    [StreetAddress]             VARCHAR (2500) NULL,
    [City]                      VARCHAR (255)  NULL,
    [State]                     VARCHAR (2)    NULL,
    [Zip]                       VARCHAR (25)   NULL,
    [Country]                   VARCHAR (2)    NULL,
    [GunlockQuantity]           SMALLINT       NULL,
    [MedEnvelopeQuantity]       SMALLINT       NULL,
    [ReviewRecordFlag]          TINYINT        NULL,
    [ReviewRecordReason]        VARCHAR (100)  NULL,
    [RecordModified]            TINYINT        NULL,
    [DoNotSend]                 TINYINT        NULL,
    [InsertDate]                DATE           NULL
);

