CREATE TABLE [EBP].[Clinician] (
    [ClinicianLastName]       VARCHAR (50)   NULL,
    [ClinicianFirstName]      VARCHAR (50)   NULL,
    [ClinicianMiddleName]     VARCHAR (50)   NULL,
    [VISN]                    TINYINT        NULL,
    [admparent_fcdm]          NVARCHAR (510) NULL,
    [StaPa]                   NVARCHAR (30)  NULL,
    [Reportingperiod]         NVARCHAR (43)  NULL,
    [Month]                   NVARCHAR (30)  NULL,
    [year]                    SMALLINT       NULL,
    [TotalSessionsAllEBPs]    INT            NULL,
    [TotalPatientsAllEBPs]    INT            NULL,
    [MH_PEI_Sessions]         INT            NULL,
    [MH_PEI_Patients]         INT            NULL,
    [MH_CPT_Sessions]         INT            NULL,
    [MH_CPT_Patients]         INT            NULL,
    [MH_CBT_D_Sessions]       INT            NULL,
    [MH_CBT_D_Patients]       INT            NULL,
    [MH_ACT_Sessions]         INT            NULL,
    [MH_ACT_Patients]         INT            NULL,
    [MH_BFT_Sessions]         INT            NULL,
    [MH_BFT_Patients]         INT            NULL,
    [MH_CBT_I_Sessions]       INT            NULL,
    [MH_CBT_I_Patients]       INT            NULL,
    [MH_IBCT_Sessions]        INT            NULL,
    [MH_IBCT_Patients]        INT            NULL,
    [MH_IPT_For_Dep_Sessions] INT            NULL,
    [MH_IPT_For_Dep_Patients] INT            NULL,
    [MH_SST_Sessions]         INT            NULL,
    [MH_SST_Patients]         INT            NULL,
    [MH_CM_Sessions]          INT            NULL,
    [MH_CM_Patients]          INT            NULL,
    [Clinician]               VARCHAR (153)  NOT NULL,
    [Date]                    DATE           NULL,
    [StaffSID]                INT            NULL,
    [Sta3n]                   SMALLINT       NULL,
    [StaffSSN]                VARCHAR (50)   NULL,
    [MH_CBTSP_Sessions]       INT            NULL,
    [MH_CBTSP_Patients]       INT            NULL,
    [MH_DBT_Sessions]         INT            NULL,
    [MH_DBT_Patients]         INT            NULL,
    [MH_PST_Sessions]         INT            NULL,
    [MH_PST_Patients]         INT            NULL,
    [MH_CB_SUD_Sessions]      INT            NULL,
    [MH_CB_SUD_Patients]      INT            NULL,
    [MH_EMDR_Sessions]        INT            NULL,
    [MH_EMDR_Patients]        INT            NULL,
    [MH_WET_Sessions]         INT            NULL,
    [MH_WET_Patients]         INT            NULL
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCIX_Clinician]
    ON [EBP].[Clinician];

